# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - iabiblica

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_d8208b44d28e40c8840f6ef84716e364 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_5e6bc9c8ff0449ab9c8b17f0f279ddaf }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_d8208b44d28e40c8840f6ef84716e364 }}/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'iabiblica'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_98cf1fd31b43472493c9cf56a7c6fe24 }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_d8208b44d28e40c8840f6ef84716e364 }}/appsvc/staticsite:${{ github.sha }}'